### ISSUE TITLE
extend import for json file

### ISSUE THREAD

**Issue by Krojan** [sndsabin/pimcore-import-bundle#5]
**config for import**
```
#config/packages/import.yaml
import:
    config:
        base_directory: '/var/www/Pimcore/import'
        customer:
            file: 'customer.json'
            mapper: 'App\Mapper\CustomerMapper'
```

**[sample customer json file](https://github.com/Krojan/pimcore-import-bundle/blob/add-json-import/Docs/Examples/import-data/customer.json)**
